- name: create a docker network
  docker_network:
          name: app-network
          driver: bridge
- name: create  the first Zookeeper server instance
  docker_container:
          name: zookeeper
          image: bitnami/zookeeper:latest
          state: started
          ports:
                  - "2181:2181"
          networks:
                  name: "{{app-network}}"
- name: Create the first node for Kafka
  docker_container:
          name: kafka1
          image: bitnami/kafka:latest
          state: started
          ports:
                  - "9092:9092"
          env:
                  "KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181"
          networks:
                  name: "{{app-network}}"

- name: Create the second node for Kafka
  docker_container:
          name: kafka2
          image: bitnami/kafka:latest
          state: started
          ports:
                  - "9092:9092"
          env:
                  "KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181"
          networks:
                  name: "{{app-network}}"

- name: Create the third node for Kafka
  docker_container:
          name: kafka3
          image: bitnami/kafka:latest
          state: started
          ports:
                  - "9092:9092"
          env:
                  "KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181"
          networks:
                  name: "{{app-network}}"

